language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("TensorCast")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TensorCast")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
